name: 'Hello World'

on: 
  [push]
      
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello world"
        
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: test_hello
        uses: ./.github/actions/hello_world
        with:
          message: " test message"
          
      - name: print context info
        run: echo "github.repo is ${{ github.repository }} "
     
      - run: echo "github.token is ${{ github.token }} "
      - run: echo "secrets is ${{ secrets.GITHUB_TOKEN }}"
